<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SNHFL9N" failures="1" tests="3" name="Test" time="8.037" errors="0" timestamp="2025-01-05T22:25:26 IST">
  <testcase classname="qa.test.testcase1" name="f1" time="0.795"/>
  <testcase classname="qa.test.testcase1" name="f2" time="0.006">
    <skipped/>
  </testcase> <!-- f2 -->
  <testcase classname="qa.test.testcase1" name="f2" time="0.002">
    <failure type="java.lang.AssertionError" message="The condition is true, so the test will fail. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The condition is true, so the test will fail. expected [false] but found [true]
at qa.test.testcase1.f2(testcase1.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
</testsuite> <!-- Test -->
